------------- REPORT QNA_ANSWER 테이블 삭제 ------------------
DROP TABLE REPORT;
DROP SEQUENCE SEQ_RNO;

DROP TABLE QNA_ANSWER;
DROP SEQUENCE SEQ_QNA_ANSWER;



--------------- 챌린지 관련 테이블 삭제 ----------------------------
-- 포인트 테이블 삭제
DROP SEQUENCE SEQ_POINT;
DROP TABLE POINT;

-- 대댓글 테이블 삭제
DROP SEQUENCE SEQ_CHAL_NESTED_REPLY;
DROP TABLE CHAL_NESTED_REPLY;

-- 댓글 테이블 삭제
DROP SEQUENCE SEQ_CHAL_REPLY;
DROP TABLE CHAL_REPLY;

-- 이달의 챌린지 참여 회원 테이블 삭제
DROP SEQUENCE SEQ_CHAL_MONTH_MEM;
DROP TABLE CHAL_MONTH_MEM;

-- 이달의 챌린지 테이블 삭제
DROP SEQUENCE SEQ_CHAL_MONTH;
DROP TABLE CHAL_MONTH;

-- 오늘의 챌린지 참여 회원 테이블 삭제
DROP SEQUENCE SEQ_CHAL_TODAY_MEM;
DROP TABLE CHAL_TODAY_MEM;

-- 오늘의 챌린지 테이블 삭제
DROP SEQUENCE SEQ_CHAL_TODAY;
DROP TABLE CHAL_TODAY;

-- 챌린지 유형 테이블 삭제
DROP SEQUENCE SEQ_CHAL;
DROP TABLE CHALLENGE;

COMMIT;


---------------------- ECOSHOP 관련 테이블 삭제 -----------------------
-- 결제수단(PAYMENT_METHOD) 테이블이 아직 남아있을 경우
-- DROP TABLE PAYMENT_METHOD;

DROP TABLE CART; 
DROP TABLE REVIEW;
DROP TABLE ORDER_DETAIL; 
DROP TABLE DELIVERY; 
DROP TABLE ORDER_SUM; 
DROP TABLE WISH;
DROP TABLE BIDDING; 
DROP TABLE APPLICATION; 
DROP TABLE PRO_INQ_ANSWER; 
DROP TABLE PRODUCT_INQUIRY; 
DROP TABLE PRODUCT_OPT; 
DROP TABLE BIDDING_BOARD; 
DROP TABLE PRODUCT_BIDDING; 
DROP TABLE PRODUCT_IMGS; 
DROP TABLE PRODUCT; 
DROP TABLE PRODUCT_STATUS; 
DROP TABLE PRODUCT_CATEGORY; 

DROP SEQUENCE SEQ_APPNO;
DROP SEQUENCE SEQ_BID_BOARDNO;
DROP SEQUENCE SEQ_BIDNO;
DROP SEQUENCE SEQ_INQNO;
DROP SEQUENCE SEQ_ORDERNO;
DROP SEQUENCE SEQ_PRONO;


-------------------- ABOUT US 관련 테이블 삭제 -----------------
DROP TABLE NOTICE;
DROP SEQUENCE SEQ_NOTICE_NO;

DROP TABLE QNA;
DROP SEQUENCE SEQ_QNA_NO;

DROP TABLE QNA_CATEGORY;


-------------------- MEMBER 테이블 삭제 ------------------------
DROP TABLE MEMBER;
DROP SEQUENCE SEQ_UNO;

COMMIT;


