---------------- FINAL 계정 생성 ----------------
--CREATE USER FINAL IDENTIFIED BY FINAL;
--GRANT RESOURCE, CONNECT TO FINAL;

---------------- MEMBER 테이블 생성 ----------------
CREATE TABLE MEMBER (
    NO NUMBER CONSTRAINT MEMBER_NO_PK PRIMARY KEY,
    ID VARCHAR2(50) CONSTRAINT MEMBER_ID_UQ UNIQUE,
    PASSWORD VARCHAR2(100),
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(300),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(300),
    POSTCODE VARCHAR2(100), 
    EXTRA_ADDRESS VARCHAR2(100), 
    DETAIL_ADDRESS VARCHAR2(100),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    MEMBER_TYPE VARCHAR2(50) DEFAULT 'USER',
    PLATFORM_TYPE VARCHAR2(100) DEFAULT 'HOMEPAGE' CONSTRAINT MEMBER_PLATFORM_TYPE_NN NOT NULL,
    IMG_NAME VARCHAR2(300),
    MODIFY_IMG_NAME VARCHAR2(300),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE DEFAULT SYSDATE
);

-- MEMBER 테이블 코멘트 입력
COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ID IS '회원ID';
COMMENT ON COLUMN MEMBER.PASSWORD IS '회원PW';
COMMENT ON COLUMN MEMBER.MEMBER_TYPE IS '회원타입';
COMMENT ON COLUMN MEMBER.NAME IS '회원명';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.PLATFORM_TYPE IS '플랫폼';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';
COMMENT ON COLUMN MEMBER.IMG_NAME IS '프로필사진';   
COMMENT ON COLUMN MEMBER.MODIFY_IMG_NAME IS '프로필사진(수정)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';   
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.POSTCODE IS '우편번호';
COMMENT ON COLUMN MEMBER.EXTRA_ADDRESS IS '참고항목';
COMMENT ON COLUMN MEMBER.DETAIL_ADDRESS IS '상세주소';

-- MEMBER 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_UNO;

-- MEMBER 테이블 데이터 입력
INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    MEMBER_TYPE,
    NAME, 
    PHONE, 
    EMAIL, 
    ADDRESS, 
    POSTCODE,
    EXTRA_ADDRESS, 
    DETAIL_ADDRESS,
    PLATFORM_TYPE, 
    STATUS, 
    IMG_NAME, 
    MODIFY_IMG_NAME, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_UNO.NEXTVAL, 
    'admin1', 
    '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
    'ADMIN', 
    '관리자1', 
    '01011111111', 
    'admin1@4earth.co.kr', 
    '서울시 강남구 역삼동',
    '16285',
    '그린타워빌딩',
    '105-4520',
    DEFAULT,
    DEFAULT,
    'giphy (1).gif',
    '20220316_104035107.gif',
    DEFAULT,
    DEFAULT
);

INSERT INTO MEMBER (
    NO, 
    ID, 
    PASSWORD, 
    MEMBER_TYPE,
    NAME, 
    PHONE, 
    EMAIL, 
    ADDRESS, 
    POSTCODE,
    EXTRA_ADDRESS, 
    DETAIL_ADDRESS,
    PLATFORM_TYPE, 
    STATUS, 
    IMG_NAME, 
    MODIFY_IMG_NAME, 
    ENROLL_DATE, 
    MODIFY_DATE
) VALUES(
    SEQ_UNO.NEXTVAL, 
    'potatoking1', 
    '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
    DEFAULT, 
    '감자킹', 
    '01000000000', 
    'potatoking1@naver.com', 
    '경기도 용인시 기흥구',
    '15321',
    '갈현마을 현대타운',
    '520',
    DEFAULT,
    DEFAULT,
    'giphy (5).gif',
    '20220317_104104010.gif',
    DEFAULT,
    DEFAULT
);

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'potatoking2', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '왕감자2', '01022222222', 'potatoking2@naver.com', '충북 청주시 서원구 충대로 1', '28644', '충북대학교', '25',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT );
                    
INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'potatoking3', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '포테토3', '01033333333', 'potatoking3@naver.com', '제주 제주시 공항로 2', '63115', '제주공항', '1층',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT );

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'potatoking4', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '감자깡4', '01044444444', 'potatoking4@naver.com', '경기 성남시 분당구 판교역로146번길 20', '13529', '현대백화점 판교점', '2층',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT );         

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'potatoking5', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '5감자', '01055550000', 'potatoking5@naver.com', '광주 서구 내방로 111', '61945', '광주광역시청', '기획팀',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT );    

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'orange1', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '오렌지1', '01066660000', 'orangeking6@naver.com', '전남 구례군 마산면 화엄사로 539', '57616', '구례화엄사', '입구',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT ); 

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'orange2', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '오렌지2', '01077770000', 'orangeking7@naver.com', '부산 연제구 거제천로270번길 30', '47518', '연서초등학교', '1-4',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT ); 

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'orange3', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '오3렌지', '01088880000', 'orangeking8@naver.com', '제주 제주시 중앙로 151', '63194', '칼호텔', '로비',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT ); 

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'orange4', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '4오렌지', '01099990000', 'orangeking9@naver.com', '충남 청양군 청양읍 학사길 55', '33303', '청양대학교', '행정실',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT ); 

INSERT INTO MEMBER (NO, ID, PASSWORD, MEMBER_TYPE, NAME, PHONE, EMAIL, ADDRESS, POSTCODE, EXTRA_ADDRESS, DETAIL_ADDRESS, 
                    PLATFORM_TYPE, STATUS, IMG_NAME, MODIFY_IMG_NAME, ENROLL_DATE, MODIFY_DATE) 
            VALUES(SEQ_UNO.NEXTVAL, 'orange5', '$2a$10$pc2aM1u/h0Vg3A4h0ZetWu.XxJcsOdSOupxBO26ll0Ee4Fqb4KY9S', 
                    DEFAULT, '오오렌지', '01010101010', 'orangeking10@naver.com', '울산 남구 팔등로 85', '44682', '울산신정푸르지오1차아파트', '105-1154',
                    DEFAULT, DEFAULT, NULL, NULL, DEFAULT, DEFAULT ); 

COMMIT;















---------------------------------------------------------------------------------------------------------------------------
-------------------------
---- 공지사항 테이블 ----
-------------------------

CREATE TABLE NOTICE (
    NOTICE_NO NUMBER CONSTRAINT NOTICE_NO_PK PRIMARY KEY,
    WRITER_NO NUMBER CONSTRAINT NOTICE_WRITER_NO_FK REFERENCES MEMBER(NO),
    NOTICE_TIT VARCHAR2(100) CONSTRAINT NOTICE_TIT_NN NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL,
    NOTICE_COUNT NUMBER DEFAULT 0,
    ORIGINAL_FILENAME VARCHAR2(100),
    RENAMED_FILENAME VARCHAR2(100),
    DATE_WRITEN DATE DEFAULT SYSDATE,
    DATE_WRITEN_MODIFY DATE DEFAULT SYSDATE,
    NOTICE_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK(NOTICE_STATUS IN('Y', 'N'))
);

---- 공지사항 코멘트 ----
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '게시글번호';
COMMENT ON COLUMN NOTICE.WRITER_NO IS '회원번호';
COMMENT ON COLUMN NOTICE.NOTICE_TIT IS '제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOTICE_COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.ORIGINAL_FILENAME IS '원본파일이름';
COMMENT ON COLUMN NOTICE.RENAMED_FILENAME IS '수정된파일이름';
COMMENT ON COLUMN NOTICE.DATE_WRITEN IS '게시글작성일';
COMMENT ON COLUMN NOTICE.DATE_WRITEN_MODIFY IS '게시글수정일';
COMMENT ON COLUMN NOTICE.NOTICE_STATUS IS '상태';

---- 공지사항 시퀀스 ----
CREATE SEQUENCE SEQ_NOTICE_NO;


---- 공지사항 더미 데이터 ----
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '송도 프리미엄 아울렛에 소분샵 입점!!', '지구를 위해 친환경 제품을 판매하는 소분샵이 드디어 송도 프리미언 아울렛에 입점했습니다~! 많은 관심과 방문 부탁드립니다!! ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '일부 상품 opp봉투 대신 썩는 속비닐로 변경', '일부 상품 opp봉투 대신 썩는 속비닐로 변경 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '2022년 설연휴 배송공지', '2022년 설연휴 배송공지 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '3월 이달의 캠페인', '3월 이달의 캠페인 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '소분샵 사은품 증정', '소분샵 사은품 증정', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '멸종위기종 동물 북클립', '멸종위기종 동물 북클립 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '소분샵 입점업체 모집', '소분샵 입점업체 모집 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '4Earth 휴면회원 관련 안내', '4Earth 휴면회원 관련 안내', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '고객상담시간 변경 안내', '고객상담시간 변경 안내 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', '뜨거워진 지구에서 우리를 구해줘', '뜨거워진 지구에서 우리를 구해줘 ', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

COMMIT;

------------------------
---- 1:1문의 테이블 ----
------------------------

---- QNA 카테고리 테이블 ----
CREATE TABLE QNA_CATEGORY (
    C_NO NUMBER(5) CONSTRAINT QNA_CATEGORY_C_NO_PK PRIMARY KEY,
    C_NAME VARCHAR2(30) CONSTRAINT QNA_CATEGORY_C_NAME_NN NOT NULL
);

COMMENT ON COLUMN QNA_CATEGORY.C_NO IS '카테고리번호';
COMMENT ON COLUMN QNA_CATEGORY.C_NAME IS '카테고리명';


---- 카테고리 데이터 ----
INSERT INTO QNA_CATEGORY VALUES (0101, '챌린지수행관련문의');
INSERT INTO QNA_CATEGORY VALUES (0102, '포인트관련문의');
INSERT INTO QNA_CATEGORY VALUES (0103, '챌린지오류관련문의');
INSERT INTO QNA_CATEGORY VALUES (0201, '구매');
INSERT INTO QNA_CATEGORY VALUES (0202, '환불');
INSERT INTO QNA_CATEGORY VALUES (0203, '포인트');
INSERT INTO QNA_CATEGORY VALUES (0301, '가입');
INSERT INTO QNA_CATEGORY VALUES (0302, '탈퇴');
INSERT INTO QNA_CATEGORY VALUES (0303, '정보수정');
INSERT INTO QNA_CATEGORY VALUES (0401, '기타');

---- 1:1문의 테이블 ----
CREATE TABLE QNA (
    QNA_NO NUMBER CONSTRAINT QNA_NO_PK PRIMARY KEY,
    WRITER_NO NUMBER CONSTRAINT QNA_WRITER_NO_FK REFERENCES MEMBER(NO),
    QNA_TIT VARCHAR2(100) CONSTRAINT QNA_TIT_NN NOT NULL,
    QNA_CAT NUMBER CONSTRAINT QNA_CAT_FK REFERENCES QNA_CATEGORY(C_NO),
    QNA_CONTENT VARCHAR2(2000) CONSTRAINT QNA_CONTENT_NN NOT NULL,
    QNA_COUNT NUMBER DEFAULT 0,
    ORIGINAL_FILENAME VARCHAR2(100),
    RENAMED_FILENAME VARCHAR2(100),
    DATE_WRITEN DATE DEFAULT SYSDATE,
    DATE_WRITEN_MODIFY DATE DEFAULT SYSDATE,
    QNA_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK(QNA_STATUS IN('Y', 'N'))
);

---- 1:1문의 코멘트----
COMMENT ON COLUMN QNA.QNA_NO IS '게시글번호';
COMMENT ON COLUMN QNA.WRITER_NO IS '회원번호';
COMMENT ON COLUMN QNA.QNA_TIT IS '제목';
COMMENT ON COLUMN QNA.QNA_CAT IS '카테고리명';
COMMENT ON COLUMN QNA.QNA_CONTENT IS '내용';
COMMENT ON COLUMN QNA.QNA_COUNT IS '조회수';
COMMENT ON COLUMN QNA.ORIGINAL_FILENAME IS '원본파일이름';
COMMENT ON COLUMN QNA.RENAMED_FILENAME IS '수정된파일이름';
COMMENT ON COLUMN QNA.DATE_WRITEN IS '게시글작성일';
COMMENT ON COLUMN QNA.DATE_WRITEN_MODIFY IS '게시글수정일';
COMMENT ON COLUMN QNA.QNA_STATUS IS '상태';

---- 1:1문의 시퀀스 ----
CREATE SEQUENCE SEQ_QNA_NO;

---- 1:1문의 더미 데이터----
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '1', '주문내역이 조회되지 않습니다.', '0201', '주문내역 확인 좀 부탁드려요!!', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '2', '입금했어요~!', '0201', '123', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '3', '챌리지 완료 했는데 이상해요', '0103', '123', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '4', '회원정보가 없다고 나오네요', '0303', '123', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
INSERT INTO QNA VALUES(SEQ_QNA_NO.NEXTVAL, '5', '세금계산서 발행 요청', '0401', '123', DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


















---------------------------------------------------------------------------------------------------------------------------
-- 챌린지 유형 테이블 생성
CREATE TABLE CHALLENGE (
    CHAL_NO NUMBER CONSTRAINT CHALLENGE_CHAL_NO_PK PRIMARY KEY,
    CHAL_CATEGORY VARCHAR2(50)
);

-- 챌린지 유형 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL;

-- 챌린지 유형 테이블 INSERT
INSERT INTO CHALLENGE (CHAL_NO, CHAL_CATEGORY) VALUES (SEQ_CHAL.NEXTVAL, '오늘의 챌린지');
INSERT INTO CHALLENGE (CHAL_NO, CHAL_CATEGORY) VALUES (SEQ_CHAL.NEXTVAL, '이달의 챌린지');

-----------------------------------------------------------------------------------------------------------------------------------------

-- 오늘의 챌린지 테이블 생성
CREATE TABLE CHAL_TODAY (
    CATEGORY NUMBER,
    CHAL_NO NUMBER CONSTRAINT CHAL_TODAY_NO_PK PRIMARY KEY,
    CHAL_TITLE VARCHAR2(1000) NOT NULL,
    CHAL_CONTENT VARCHAR2(4000) NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(4000) NOT NULL,
    RENAMED_FILENAME VARCHAR2(4000) NOT NULL,
    CHAL_POINT NUMBER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CHAL_STATUS CHAR DEFAULT 'N' CHECK(CHAL_STATUS IN('Y', 'N')) NOT NULL
);

-- 오늘의 챌린지 테이블 컬럼 설명
COMMENT ON COLUMN CHAL_TODAY.CATEGORY IS '분류(오늘/이달)';
COMMENT ON COLUMN CHAL_TODAY.CHAL_NO IS '오늘의 챌린지 번호';
COMMENT ON COLUMN CHAL_TODAY.CHAL_TITLE IS '오늘의 챌린지 제목';
COMMENT ON COLUMN CHAL_TODAY.CHAL_CONTENT IS '오늘의 챌린지 내용';
COMMENT ON COLUMN CHAL_TODAY.ORIGINAL_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_TODAY.RENAMED_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_TODAY.CHAL_POINT IS '달성 시 지급 포인트';
COMMENT ON COLUMN CHAL_TODAY.START_DATE IS '게시 시작일';
COMMENT ON COLUMN CHAL_TODAY.END_DATE IS '게시 종료일';
COMMENT ON COLUMN CHAL_TODAY.CHAL_STATUS IS '게시 상태';

-- 오늘의 챌린지 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL_TODAY;

-- 오늘의 챌린지 더미 데이터 INSERT
INSERT INTO CHAL_TODAY (CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, START_DATE, END_DATE, CHAL_STATUS)
    VALUES (1, SEQ_CHAL_TODAY.NEXTVAL, '걸어서 or 자전거로 출퇴근 하기', '대기오염물질을 발생시키는 차량 운행을 줄이고 걸어서 출퇴근 하거나 자전거로 출퇴근하여 하루를 시작해보세요. 출퇴근이 아니더라도 가까운 거리는 두 발로 이동하는 습관을 가져보는 건 어떨까요?', 'challenge_today01.jpg', 'challenge_today01.jpg', 5000, SYSDATE, SYSDATE, 'Y');
INSERT INTO CHAL_TODAY (CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, START_DATE, END_DATE, CHAL_STATUS)
    VALUES (1, SEQ_CHAL_TODAY.NEXTVAL, '하루 한 끼 채식하기', '한 사람당 1주일에 하루만 채식을 해도 1년에 나무 15그루를 심는 효과가 있다고 합니다. 채식으로 몸을 가볍게 하고  육류를 생산하는 과정에서 배출되는 탄소를 조금이라도 줄일 수 있는 효과가 있습니다.', 'challenge_today02.jpg', 'challenge_today02.jpg', 5000, SYSDATE, SYSDATE, 'Y');
INSERT INTO CHAL_TODAY (CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, START_DATE, END_DATE, CHAL_STATUS)
    VALUES (1, SEQ_CHAL_TODAY.NEXTVAL, '텀블러 사용하기', '일회용 플라스틱 사용을 자제하고 다회 사용 가능한 텀블러를 사용해보세요. 플라스틱은 바다에서 분해되어 미세 플라스틱이 되면 해양생물의 생명을 위협하게 됩니다.', 'challenge_today03.jpg', 'challenge_today03.jpg', 5000, SYSDATE, SYSDATE, 'Y');
INSERT INTO CHAL_TODAY (CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, START_DATE, END_DATE, CHAL_STATUS)
    VALUES (1, SEQ_CHAL_TODAY.NEXTVAL, '메일함 비우기', '메일을 보관하는 데이터 센터는 24시간 가동되어야 하기 때문에 엄청난 전기가 필요합니다. 메일 한 통은 4g의 이산화탄소를 배출한다고 합니다. 메일함 1GB를 비우면 14.9kg의 이산화탄소 배출을 감축할 수 있습니다.', 'challenge_today04.jpg', 'challenge_today04.jpg', 5000, SYSDATE, SYSDATE, 'Y');

--BEGIN
--    FOR N IN 1..4
--    LOOP
--        INSERT INTO CHAL_TODAY VALUES(1, SEQ_CHAL_TODAY.NEXTVAL, '챌린지 제목 ' || SEQ_CHAL_TODAY.CURRVAL, '챌린지 내용 ' || SEQ_CHAL_TODAY.CURRVAL, 'challenge_today02.jpg', 'challenge_today02.jpg', 5000, TO_DATE('2022-03-14', 'yyyy/MM/dd'), TO_DATE('2022-03-14', 'yyyy/MM/dd'), 'Y');
--    END LOOP;
--    COMMIT;
--EXCEPTION
--    WHEN OTHERS THEN ROLLBACK;
--END;
--/
--
--BEGIN
--    FOR N IN 1..4
--    LOOP
--        INSERT INTO CHAL_TODAY VALUES(1, SEQ_CHAL_TODAY.NEXTVAL, '챌린지 제목 ' || SEQ_CHAL_TODAY.CURRVAL, '챌린지 내용 ' || SEQ_CHAL_TODAY.CURRVAL, 'challenge_today02.jpg', 'challenge_today02.jpg', 5000, TO_DATE('2022-03-15', 'yyyy/MM/dd'), TO_DATE('2022-03-15', 'yyyy/MM/dd'), 'Y');
--    END LOOP;
--    COMMIT;
--EXCEPTION
--    WHEN OTHERS THEN ROLLBACK;
--END;
--/


-----------------------------------------------------------------------------------------------------------------------------------------

-- 오늘의 챌린지 참여 회원 테이블 생성
CREATE TABLE CHAL_TODAY_MEM (
    NO NUMBER CONSTRAINT CHAL_TODAY_MEM_NO_PK PRIMARY KEY,
    MEM_NO NUMBER CONSTRAINT CHAL_TODAY_MEM_MEM_NO_FK REFERENCES MEMBER(NO),
    CHAL_NO NUMBER NOT NULL,
    CHAL_DATE DATE DEFAULT SYSDATE NOT NULL,
    CHAL_STATUS CHAR DEFAULT 'Y' CHECK(CHAL_STATUS IN('Y', 'N')),
    ORIGINAL_FILENAME VARCHAR2(1000) NOT NULL,
    RENAMED_FILENAME VARCHAR2(4000) NOT NULL,
    CHAL_POINT NUMBER NOT NULL,
    CHAL_POINT_STATUS CHAR DEFAULT 'N' CHECK(CHAL_POINT_STATUS IN('Y', 'N'))
);

-- 오늘의 챌린지 참여 회원 테이블 컬럼 설명
COMMENT ON COLUMN CHAL_TODAY_MEM.NO IS '오늘의 챌린지 참여 번호';
COMMENT ON COLUMN CHAL_TODAY_MEM.MEM_NO IS '회원 번호';
COMMENT ON COLUMN CHAL_TODAY_MEM.CHAL_NO IS '오늘의 챌린지 고유 번호';
COMMENT ON COLUMN CHAL_TODAY_MEM.CHAL_DATE IS '달성일';
COMMENT ON COLUMN CHAL_TODAY_MEM.CHAL_STATUS IS '달성 상태';
COMMENT ON COLUMN CHAL_TODAY_MEM.ORIGINAL_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_TODAY_MEM.RENAMED_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_TODAY_MEM.CHAL_POINT IS '달성 시 지급 포인트';
COMMENT ON COLUMN CHAL_TODAY_MEM.CHAL_POINT_STATUS IS '포인트 지급 상태';

-- 오늘의 챌린지 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL_TODAY_MEM;


-----------------------------------------------------------------------------------------------------------------------------------------

-- 이달의 챌린지 테이블 생성
CREATE TABLE CHAL_MONTH (
    CATEGORY NUMBER,
    CHAL_NO NUMBER CONSTRAINT CHAL_MONTH_CHAL_NO_PK PRIMARY KEY,
    CHAL_TITLE VARCHAR2(1000) NOT NULL,
    CHAL_CONTENT VARCHAR2(4000) NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(4000) NOT NULL,
    RENAMED_FILENAME VARCHAR2(4000) NOT NULL,
    CHAL_POINT NUMBER NOT NULL,
    CHAL_COUNT NUMBER DEFAULT 5 CHECK(CHAL_COUNT IN(5, 10)),
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    CHAL_STATUS CHAR DEFAULT 'Y' CHECK(CHAL_STATUS IN('Y', 'N')) NOT NULL
);

-- 이달의 챌린지 테이블 컬럼 설명
COMMENT ON COLUMN CHAL_MONTH.CATEGORY IS '분류(오늘/이달)';
COMMENT ON COLUMN CHAL_MONTH.CHAL_NO IS '이달의 챌린지 번호';
COMMENT ON COLUMN CHAL_MONTH.CHAL_TITLE IS '이달의 챌린지 제목';
COMMENT ON COLUMN CHAL_MONTH.CHAL_CONTENT IS '이달의 챌린지 내용';
COMMENT ON COLUMN CHAL_MONTH.ORIGINAL_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_MONTH.RENAMED_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_MONTH.CHAL_POINT IS '달성 시 지급 예정 포인트';
COMMENT ON COLUMN CHAL_MONTH.CHAL_COUNT IS '필요 달성 횟수';
COMMENT ON COLUMN CHAL_MONTH.START_DATE IS '게시 시작일';
COMMENT ON COLUMN CHAL_MONTH.END_DATE IS '게시 종료일';
COMMENT ON COLUMN CHAL_MONTH.CHAL_STATUS IS '게시 상태';

-- 이달의 챌린지 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL_MONTH;

-- 이달의 챌린지 테이블 INSERT
BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 1000, 5, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 1500, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 2000, 5, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 2500, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP; 
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 3000, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 3500, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 4000, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

BEGIN
    FOR N IN 1..5
    LOOP
        INSERT INTO CHAL_MONTH VALUES(2, SEQ_CHAL_MONTH.NEXTVAL, '이달의 챌린지 제목 ' || SEQ_CHAL_MONTH.CURRVAL, '이달의 챌린지 내용 ' || SEQ_CHAL_MONTH.CURRVAL, 'challenge_today03.jpg', 'challenge_today03.jpg', 4500, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT);
    END LOOP;  
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '용기내 챌린지', '포장 주문 시 다회용기를 사용해보세요. 플라스틱 사용을 줄일 수 있습니다.', 'challenge_month01.jpg', 'challenge_month01.jpg', 5000, 5, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '천연 수세미 사용하기', '수세미에도 미세 플라스틱이 들어있는 것을 알고 계신가요? 저렴하고 다회 사용이 가능한 천연 수세미를 사용해보세요.', 'challenge_month02.jpg', 'challenge_month02.jpg', 2000, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '에코백 사용하기', '가볍고 편리한 에코백을 사용하여 플라스틱 비닐봉투의 사용을 줄일 수 있습니다.', 'challenge_month03.jpg', 'challenge_month03.jpg', 2500, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '고체 샴푸 사용하기', '플라스틱 용기가 필요없는 고체 샴푸 및 바디워시의 사용을 생활화해보세요. 친환경 제품으로 피부 개선도 기대할 수 있습니다.', 'challenge_month04.jpg', 'challenge_month04.jpg', 3000, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '모바일 영수증 받기', '불필요한 영수증은 받지 않고 필요하다면 모바일 영수증을 이용해보세요. 재활용이 불가능한 종이의 사용을 줄일 수 있습니다.', 'challenge_month05.jpg', 'challenge_month05.jpg', 1500, 5, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '리필 상품 구매하기', '더 저렴한 리필 상품을 구매하여 절약과 환경 보호를 실천하세요. 플라스틱 사용을 줄일 수 있습니다.', 'challenge_month06.jpg', 'challenge_month06.jpg', 3000, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '메일함 비우기', '메일함 1GB를 비우면 14.9kg의 이산화탄소 배출을 감축할 수 있습니다.', 'challenge_month07.jpg', 'challenge_month07.jpg', 3300, 10, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);
INSERT INTO CHAL_MONTH (
    CATEGORY, CHAL_NO, CHAL_TITLE, CHAL_CONTENT, ORIGINAL_FILENAME, RENAMED_FILENAME, CHAL_POINT, CHAL_COUNT, START_DATE, END_DATE, CHAL_STATUS
) VALUES (
    2, SEQ_CHAL_MONTH.NEXTVAL, '냉장고 파먹기', '버리는 식재료가 없도록 필요한 양의 재료만 구매하고 남는 재료는 또 다른 요리로 탄생시켜 보세요!', 'challenge_month08.jpg', 'challenge_month08.jpg', 2000, 5, SYSDATE, TO_DATE('2022-05-12', 'yyyy/MM/dd'), DEFAULT
);

-----------------------------------------------------------------------------------------------------------------------------------------

-- 이달의 챌린지 참여 회원 테이블 생성
CREATE TABLE CHAL_MONTH_MEM (
    NO NUMBER CONSTRAINT CHAL_MONTH_MEM_NO_PK PRIMARY KEY,
    MEM_NO NUMBER CONSTRAINT CHAL_MONTH_MEM_MEM_NO_FK REFERENCES MEMBER(NO),
    CHAL_NO NUMBER NOT NULL,
    CHAL_DATE DATE DEFAULT SYSDATE NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(1000),
    RENAMED_FILENAME VARCHAR2(4000),
    MY_COUNT NUMBER NOT NULL,
    CHAL_STATUS CHAR DEFAULT 'Y' CHECK(CHAL_STATUS IN('Y', 'N')),
    CHAL_POINT NUMBER NOT NULL,
    CHAL_POINT_STATUS CHAR DEFAULT 'N' CHECK(CHAL_POINT_STATUS IN('Y', 'N'))
);

-- 이달의 챌린지 참여 회원 테이블 컬럼 설명
COMMENT ON COLUMN CHAL_MONTH_MEM.NO IS '챌린지 참여 번호';
COMMENT ON COLUMN CHAL_MONTH_MEM.MEM_NO IS '회원 번호';
COMMENT ON COLUMN CHAL_MONTH_MEM.CHAL_NO IS '챌린지 고유 번호';
COMMENT ON COLUMN CHAL_MONTH_MEM.CHAL_DATE IS '달성일';
COMMENT ON COLUMN CHAL_MONTH_MEM.ORIGINAL_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_MONTH_MEM.RENAMED_FILENAME IS '이미지 파일명';
COMMENT ON COLUMN CHAL_MONTH_MEM.MY_COUNT IS '사용자 달성 횟수';
COMMENT ON COLUMN CHAL_MONTH_MEM.CHAL_STATUS IS '달성 상태';
COMMENT ON COLUMN CHAL_MONTH_MEM.CHAL_POINT IS '지급 포인트';
COMMENT ON COLUMN CHAL_MONTH_MEM.CHAL_POINT_STATUS IS '포인트 지급 상태';

-- 이달의 챌린지 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL_MONTH_MEM;


-----------------------------------------------------------------------------------------------------------------------------------------

-- 댓글 테이블 생성
CREATE TABLE CHAL_REPLY (
    REPLY_NO NUMBER CONSTRAINT CHAL_PEPLY_NO_PK PRIMARY KEY,
    MEM_NO NUMBER CONSTRAINT CHAL_REPLY_MEM_NO_FK REFERENCES MEMBER(NO),
    CHAL_NO NUMBER CONSTRAINT CHAL_REPLY_CHAL_NO_FK REFERENCES CHAL_MONTH(CHAL_NO),
    CONTENT VARCHAR2(4000),
    REPLY_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE
);

-- 댓글 테이블 컬럼 설명
COMMENT ON COLUMN CHAL_REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN CHAL_REPLY.CHAL_NO IS '챌린지 번호';
COMMENT ON COLUMN CHAL_REPLY.CONTENT IS '댓글 내용';
COMMENT ON COLUMN CHAL_REPLY.REPLY_DATE IS '작성일';
COMMENT ON COLUMN CHAL_REPLY.MODIFY_DATE IS '수정일';

-- 댓글 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL_REPLY;


-----------------------------------------------------------------------------------------------------------------------------------------

-- 대댓글 테이블 생성
CREATE TABLE CHAL_NESTED_REPLY (
    NESTED_REPLY_NO NUMBER CONSTRAINT CHAL_NESTED_REPLY_NO_PK PRIMARY KEY,
    REPLY_NO NUMBER CONSTRAINT CHAL_NESTED_REPLY_REPLY_NO_FK REFERENCES CHAL_REPLY(REPLY_NO),
    MEM_NO NUMBER CONSTRAINT CHAL_NESTED_REPLY_MEM_NO_FK REFERENCES MEMBER(NO),
    CHAL_NO NUMBER,
    CONTENT VARCHAR2(4000),
    REPLY_DATE DATE DEFAULT SYSDATE,
    MODIFY_DATE DATE,
    NESTED_REPLY_STATUS CHAR DEFAULT 'Y' CHECK(NESTED_REPLY_STATUS IN('Y', 'N'))
);

-- 대댓글 테이블 컬럼 설명
COMMENT ON COLUMN CHAL_NESTED_REPLY.NESTED_REPLY_NO IS '대댓글 번호';
COMMENT ON COLUMN CHAL_NESTED_REPLY.REPLY_NO IS '댓글 번호';
COMMENT ON COLUMN CHAL_NESTED_REPLY.CHAL_NO IS '챌린지 번호';
COMMENT ON COLUMN CHAL_NESTED_REPLY.CONTENT IS '댓글 내용';
COMMENT ON COLUMN CHAL_NESTED_REPLY.REPLY_DATE IS '작성일';
COMMENT ON COLUMN CHAL_NESTED_REPLY.MODIFY_DATE IS '수정일';
COMMENT ON COLUMN CHAL_NESTED_REPLY.NESTED_REPLY_STATUS IS '게시 상태';

-- 대댓글 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_CHAL_NESTED_REPLY;


-------------------------------------------------------------------------------------------


-- 포인트 테이블 생성
CREATE TABLE POINT (
    POINT_NO NUMBER CONSTRAINT POINT_NO_PK PRIMARY KEY,
    MEM_NO NUMBER CONSTRAINT POINT_MEM_NO_FK REFERENCES MEMBER(NO),
    SAVE_DATE DATE DEFAULT SYSDATE,
    SAVE_CONTENT VARCHAR2(1000),
    SAVE_POINT NUMBER,
    SPEND_DATE DATE DEFAULT SYSDATE,
    SPEND_CONTENT VARCHAR2(1000),
    SPEND_POINT NUMBER,
    DISAPEAR_DATE DATE,
    POINT_CATEGORY CHAR DEFAULT 1 CHECK(POINT_CATEGORY IN(1, 2)),
    SAVE_STATUS CHAR DEFAULT 'Y' CHECK(SAVE_STATUS IN('Y', 'N'))
);

-- 포인트 테이블 컬럼 설명
COMMENT ON COLUMN POINT.POINT_NO IS '댓글 번호';
COMMENT ON COLUMN POINT.MEM_NO IS '회원 번호';
COMMENT ON COLUMN POINT.SAVE_DATE IS '적립일';
COMMENT ON COLUMN POINT.SAVE_CONTENT IS '적립 내용';
COMMENT ON COLUMN POINT.SAVE_POINT IS '적립 포인트';
COMMENT ON COLUMN POINT.SPEND_DATE IS '사용일';
COMMENT ON COLUMN POINT.SPEND_CONTENT IS '사용 내용';
COMMENT ON COLUMN POINT.SPEND_POINT IS '사용 포인트';
COMMENT ON COLUMN POINT.DISAPEAR_DATE IS '소멸 예정일';
COMMENT ON COLUMN POINT.POINT_CATEGORY IS '포인트 분류(1:적립/ 2:사용)';

-- 포인트 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_POINT;

-------------------------------------------------------------------------------------------

COMMIT;











---------------------------------------------------------------------------------------------------------------------------
------------------------ 에코샵 ------------------------
------------------------
---- 상품 관련 테이블 ----
------------------------
-- 상품 상태 테이블
CREATE TABLE PRODUCT_STATUS (
    S_NO NUMBER(3) CONSTRAINT S_NO_PK PRIMARY KEY,
    S_NAME VARCHAR2(20) CONSTRAINT S_NAME_NN NOT NULL
);

COMMENT ON COLUMN PRODUCT_STATUS.S_NO IS '상태번호';
COMMENT ON COLUMN PRODUCT_STATUS.S_NAME IS '상태명';

-- 상품 상태 데이터
INSERT INTO PRODUCT_STATUS VALUES (0, '모집대기');
INSERT INTO PRODUCT_STATUS VALUES (1, '모집중');
INSERT INTO PRODUCT_STATUS VALUES (2, '모집성공');
INSERT INTO PRODUCT_STATUS VALUES (3, '판매중');
INSERT INTO PRODUCT_STATUS VALUES (4, '일시품절');
INSERT INTO PRODUCT_STATUS VALUES (5, '판매중지');

-- 카테고리 테이블
CREATE TABLE PRODUCT_CATEGORY (
    C_NO NUMBER(5) CONSTRAINT C_NO_PK PRIMARY KEY,
    C_NAME VARCHAR2(20) CONSTRAINT C_NAME_NN NOT NULL
);

COMMENT ON COLUMN PRODUCT_CATEGORY.C_NO IS '카테고리번호';
COMMENT ON COLUMN PRODUCT_CATEGORY.C_NAME IS '카테고리명';

-- 상품 카테고리 데이터
INSERT INTO PRODUCT_CATEGORY VALUES (0101, '간편식');
INSERT INTO PRODUCT_CATEGORY VALUES (0102, '디저트/간식');
INSERT INTO PRODUCT_CATEGORY VALUES (0103, '건조식품');
INSERT INTO PRODUCT_CATEGORY VALUES (0201, '세탁');
INSERT INTO PRODUCT_CATEGORY VALUES (0202, '주방');
INSERT INTO PRODUCT_CATEGORY VALUES (0203, '욕실');
INSERT INTO PRODUCT_CATEGORY VALUES (0301, '바디케어');
INSERT INTO PRODUCT_CATEGORY VALUES (0302, '기초화장품');
INSERT INTO PRODUCT_CATEGORY VALUES (0303, '메이크업');
INSERT INTO PRODUCT_CATEGORY VALUES (0304, '헤어케어');
INSERT INTO PRODUCT_CATEGORY VALUES (0401, '강아지');
INSERT INTO PRODUCT_CATEGORY VALUES (0402, '고양이');

-- 상품 테이블
CREATE TABLE PRODUCT (
    PRO_NO NUMBER CONSTRAINT PRO_NO_PK PRIMARY KEY,
    PRO_NAME VARCHAR2(40) CONSTRAINT PRO_NAME_NN NOT NULL,
    PRO_PRICE NUMBER CONSTRAINT PRO_PRICE_NN NOT NULL,
    PRO_MODIFY_DATE DATE DEFAULT SYSDATE,
    PRO_VOL VARCHAR2(20),
    PRO_IMG VARCHAR2(400),
    PRO_MODIFY_IMG VARCHAR2(300),
    PRO_INFO VARCHAR2(4000),
    PRO_STAT NUMBER CONSTRAINT PRO_STAT_FK REFERENCES PRODUCT_STATUS,
    PRO_CAT NUMBER CONSTRAINT PRO_CAT_FK REFERENCES PRODUCT_CATEGORY,
    PRO_STOCK NUMBER(20),
    PRO_SOLD NUMBER(20),
    PRO_DATE DATE DEFAULT SYSDATE,
    PRO_MFG VARCHAR2(40) CONSTRAINT PRO_MFG_NN NOT NULL,
    PRO_RATING NUMBER(3, 1) DEFAULT 0
);

COMMENT ON COLUMN PRODUCT.PRO_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT.PRO_NAME IS '상품명';
COMMENT ON COLUMN PRODUCT.PRO_PRICE IS '가격';
COMMENT ON COLUMN PRODUCT.PRO_MODIFY_DATE IS '상태수정일';
COMMENT ON COLUMN PRODUCT.PRO_VOL IS '용량';
COMMENT ON COLUMN PRODUCT.PRO_IMG IS '상품사진';
COMMENT ON COLUMN PRODUCT.PRO_MODIFY_IMG IS '상품사진수정';
COMMENT ON COLUMN PRODUCT.PRO_INFO IS '상품정보';
COMMENT ON COLUMN PRODUCT.PRO_STAT IS '상품상태번호';
COMMENT ON COLUMN PRODUCT.PRO_CAT IS '상품카테고리번호';
COMMENT ON COLUMN PRODUCT.PRO_STOCK IS '재고';
COMMENT ON COLUMN PRODUCT.PRO_SOLD IS '판매량';
COMMENT ON COLUMN PRODUCT.PRO_DATE IS '등록일';
COMMENT ON COLUMN PRODUCT.PRO_MFG IS '제조사';
COMMENT ON COLUMN PRODUCT.PRO_RATING IS '별점';

-- 상품번호 시퀀스 생성
CREATE SEQUENCE SEQ_PRONO;

-- 상품 슬라이더 이미지 테이블
CREATE TABLE PRODUCT_IMGS (
    PRO_NO NUMBER CONSTRAINT PRO_IMGS_PRO_NO_FK REFERENCES PRODUCT(PRO_NO),
    ORIGINAL_FILENAME VARCHAR2(100), 
    RENAMED_FILENAME VARCHAR2(100)
);

COMMENT ON COLUMN PRODUCT_IMGS.PRO_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT_IMGS.ORIGINAL_FILENAME IS '상세사진원본이름';
COMMENT ON COLUMN PRODUCT_IMGS.RENAMED_FILENAME IS '상세사진수정이름';

-- 상품 옵션 테이블
CREATE TABLE PRODUCT_OPT (
    PRO_NO NUMBER CONSTRAINT PRODUCT_OPT_PRO_NO_FK REFERENCES PRODUCT(PRO_NO),
    O_NO NUMBER(3),
    O_NAME VARCHAR2(40),
    
    CONSTRAINT PRODUCT_OPT_PK PRIMARY KEY(PRO_NO, O_NO)
);

COMMENT ON COLUMN PRODUCT_OPT.PRO_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT_OPT.O_NO IS '옵션번호';
COMMENT ON COLUMN PRODUCT_OPT.O_NAME IS '옵션명';

-- 상품 문의 테이블
CREATE TABLE PRODUCT_INQUIRY (
   PRO_NO NUMBER CONSTRAINT PRO_INQ_PRO_NO_FK REFERENCES PRODUCT(PRO_NO),
   MEMBER_NO NUMBER CONSTRAINT PRO_INQ_MEMBER_NO_FK REFERENCES MEMBER(NO),
   INQ_NO NUMBER,
   INQ_DATE DATE DEFAULT SYSDATE,
   INQ_MOD_DATE DATE DEFAULT SYSDATE,
   INQ_TITLE VARCHAR2(100) CONSTRAINT PRO_INQ_TIT_NN NOT NULL,
   INQ_CONTENT VARCHAR2(4000) CONSTRAINT PRO_INQ_CTT_NN NOT NULL,
   INQ_STAT VARCHAR2(2) CHECK(INQ_STAT IN('Y', 'N')),
   INQ_SECRET VARCHAR2(2) CHECK(INQ_SECRET IN('Y', 'N')),
   
   CONSTRAINT PRO_INQ_PK PRIMARY KEY(PRO_NO, MEMBER_NO, INQ_NO)
);

COMMENT ON COLUMN PRODUCT_INQUIRY.PRO_NO IS '상품번호';
COMMENT ON COLUMN PRODUCT_INQUIRY.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_NO IS '문의번호';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_DATE IS '작성일';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_MOD_DATE IS '수정일';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_TITLE IS '문의제목';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_CONTENT IS '문의내용';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_STAT IS '답변상태';
COMMENT ON COLUMN PRODUCT_INQUIRY.INQ_STAT IS '비밀글 여부';

-- 문의번호 시퀀스 생성
CREATE SEQUENCE SEQ_INQNO;

-- 상품 문의 답변 테이블
CREATE TABLE PRO_INQ_ANSWER (
    PRO_NO NUMBER,
    MEMBER_NO NUMBER,
    INQ_NO NUMBER,
    INQ_ANS VARCHAR2(4000) CONSTRAINT PRO_INQ_ANS_NN NOT NULL,
    INQ_ANS_DATE DATE DEFAULT SYSDATE,
    
    FOREIGN KEY(PRO_NO, MEMBER_NO, INQ_NO) REFERENCES PRODUCT_INQUIRY,
    CONSTRAINT PRO_INQ_ANS_PK PRIMARY KEY(PRO_NO, MEMBER_NO, INQ_NO)
);

COMMENT ON COLUMN PRO_INQ_ANSWER.PRO_NO IS '상품번호';
COMMENT ON COLUMN PRO_INQ_ANSWER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN PRO_INQ_ANSWER.INQ_NO IS '문의번호';
COMMENT ON COLUMN PRO_INQ_ANSWER.INQ_ANS IS '답변내용';
COMMENT ON COLUMN PRO_INQ_ANSWER.INQ_ANS_DATE IS '답변작성일';

COMMIT;

------------------------
--- 찜 & 장바구니 테이블 ---
------------------------
-- 찜 테이블
CREATE TABLE WISH (
    PRO_NO NUMBER CONSTRAINT WISH_PRO_NO_FK REFERENCES PRODUCT(PRO_NO),
    WISH_STAT VARCHAR2(2) CHECK(WISH_STAT IN('Y', 'N')),
    MEMBER_NO NUMBER CONSTRAINT WISH_MEMBER_NO_FK REFERENCES MEMBER(NO),
    WISH_DATE DATE DEFAULT SYSDATE,    
    
    CONSTRAINT WISH_PK PRIMARY KEY(MEMBER_NO, PRO_NO)
);

COMMENT ON COLUMN WISH.PRO_NO IS '상품번호';
COMMENT ON COLUMN WISH.WISH_STAT IS '찜 상태';
COMMENT ON COLUMN WISH.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN WISH.WISH_DATE IS '찜 수정일';

-- 장바구니 테이블
CREATE TABLE CART (
    MEMBER_NO NUMBER CONSTRAINT CART_MEMBER_NO_FK REFERENCES MEMBER(NO),
    PRO_NO NUMBER,
    PRO_OPT NUMBER,
    CART_QTY NUMBER(4),
    CART_STAT VARCHAR2(2) CHECK(CART_STAT IN('Y', 'N')),
    CART_DATE DATE DEFAULT SYSDATE,
    
    FOREIGN KEY(PRO_NO, PRO_OPT) REFERENCES PRODUCT_OPT,
    CONSTRAINT CART_PK PRIMARY KEY(MEMBER_NO, PRO_NO, PRO_OPT)
);

COMMENT ON COLUMN CART.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN CART.PRO_NO IS '상품 번호';
COMMENT ON COLUMN CART.PRO_OPT IS '상품 옵션 번호';
COMMENT ON COLUMN CART.CART_QTY IS '상품수량';
COMMENT ON COLUMN CART.CART_STAT IS '장바구니 상태';
COMMENT ON COLUMN CART.CART_DATE IS '장바구니 수정일';

COMMIT;

------------------------
---- 모집 관련 테이블 ----
------------------------
-- 상품 등록 신청 테이블
CREATE TABLE APPLICATION (
    APP_NO NUMBER CONSTRAINT APPLICATION_NO_PK PRIMARY KEY,
    MEMBER_NO NUMBER CONSTRAINT APP_MEMBER_NO_FK REFERENCES MEMBER(NO),    
    APP_NAME VARCHAR2(100),
    APP_URL VARCHAR2(4000),
    APP_TITLE VARCHAR2(100) CONSTRAINT APP_TITLE_NN NOT NULL,
    APP_CONTENT VARCHAR2(4000),
    APP_S_NO NUMBER CONSTRAINT APP_S_NO_FK REFERENCES PRODUCT_STATUS(S_NO),
    APP_C_NO NUMBER CONSTRAINT APP_C_NO_FK REFERENCES PRODUCT_CATEGORY(C_NO),
    APP_DATE DATE DEFAULT SYSDATE    
);

COMMENT ON COLUMN APPLICATION.APP_NO IS '신청번호';
COMMENT ON COLUMN APPLICATION.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN APPLICATION.APP_NAME IS '상품이름';
COMMENT ON COLUMN APPLICATION.APP_URL IS '상품링크';
COMMENT ON COLUMN APPLICATION.APP_TITLE IS '제목';
COMMENT ON COLUMN APPLICATION.APP_CONTENT IS '내용';
COMMENT ON COLUMN APPLICATION.APP_S_NO IS '상품상태번호';
COMMENT ON COLUMN APPLICATION.APP_C_NO IS '상품카테고리번호';
COMMENT ON COLUMN APPLICATION.APP_DATE IS '작성일';

-- 신청번호 시퀀스 생성
CREATE SEQUENCE SEQ_APPNO;

-- 모집중인 상품 테이블
CREATE TABLE PRODUCT_BIDDING (
    BID_NO NUMBER CONSTRAINT PRO_BID_NO_PK PRIMARY KEY,
    BID_NAME VARCHAR2(50) CONSTRAINT PRO_BID_NAME_NN NOT NULL,
    BID_COND NUMBER CONSTRAINT PRO_BID_CONT_NN NOT NULL,
    BID_CURR NUMBER,
    BID_S_NO NUMBER CONSTRAINT PRO_BID_S_NO_FK REFERENCES PRODUCT_STATUS(S_NO),
    BID_URL VARCHAR2(4000),
    ORIGINAL_FILENAME VARCHAR2(2000),
    RENAMED_FILENAME VARCHAR2(2000)
);

COMMENT ON COLUMN PRODUCT_BIDDING.BID_NO IS '모집번호';
COMMENT ON COLUMN PRODUCT_BIDDING.BID_NAME IS '상품이름';
COMMENT ON COLUMN PRODUCT_BIDDING.BID_COND IS '필요인원';
COMMENT ON COLUMN PRODUCT_BIDDING.BID_CURR IS '현재인원';
COMMENT ON COLUMN PRODUCT_BIDDING.BID_S_NO IS '상품상태번호';
COMMENT ON COLUMN PRODUCT_BIDDING.BID_URL IS '상품링크';
COMMENT ON COLUMN PRODUCT_BIDDING.ORIGINAL_FILENAME IS '상세사진원본이름';
COMMENT ON COLUMN PRODUCT_BIDDING.RENAMED_FILENAME IS '상세사진수정이름';

CREATE SEQUENCE SEQ_BIDNO;

-- 모집 참여 테이블
CREATE TABLE BIDDING (
    BID_NO NUMBER CONSTRAINT BID_NO_FK REFERENCES PRODUCT_BIDDING(BID_NO),
    BID_MEMBER_NO NUMBER CONSTRAINT BID_MEM_NO_FK REFERENCES MEMBER(NO),
    BID_STAT VARCHAR2(2) CHECK(BID_STAT IN('Y', 'N')),
    
    CONSTRAINT BID_PK PRIMARY KEY(BID_NO, BID_MEMBER_NO)
);

COMMENT ON COLUMN BIDDING.BID_NO IS '모집번호';
COMMENT ON COLUMN BIDDING.BID_MEMBER_NO IS '회원번호';
COMMENT ON COLUMN BIDDING.BID_STAT IS '참여상태';

-- 모집 참여자 한마디 게시판
CREATE TABLE BIDDING_BOARD (
    BOARD_NO NUMBER CONSTRAINT BID_BOARD_NO_PK PRIMARY KEY,
    MEMBER_NO NUMBER CONSTRAINT BID_BOARD_MEM_NO_FK REFERENCES MEMBER(NO),
    BID_NO NUMBER CONSTRAINT BID_BOARD_BID_NO_FK REFERENCES PRODUCT_BIDDING(BID_NO),
    BOARD_CONTENT VARCHAR2(1000),
    BOARD_DATE DATE DEFAULT SYSDATE,
    BOARD_STAT VARCHAR2(2) CHECK(BOARD_STAT IN('Y', 'N'))
);

CREATE SEQUENCE SEQ_BID_BOARDNO;

COMMENT ON COLUMN BIDDING_BOARD.BOARD_NO IS '댓글 번호';
COMMENT ON COLUMN BIDDING_BOARD.MEMBER_NO IS '회원 번호';
COMMENT ON COLUMN BIDDING_BOARD.BID_NO IS '모집 번호';
COMMENT ON COLUMN BIDDING_BOARD.BOARD_CONTENT IS '댓글 내용';
COMMENT ON COLUMN BIDDING_BOARD.BOARD_DATE IS '작성일';
COMMENT ON COLUMN BIDDING_BOARD.BOARD_STAT IS '댓글 상태';

COMMIT;

------------------------
---- 주문 관련 테이블 ----
------------------------
-- 주문 테이블
CREATE TABLE ORDER_SUM (
    ORDER_NO NUMBER CONSTRAINT O_NO_PK PRIMARY KEY,
    MEMBER_NO NUMBER CONSTRAINT O_MEMBER_NO_FK REFERENCES MEMBER(NO),
    ORDER_PRICE NUMBER,
    ORDER_STAT VARCHAR2(20) DEFAULT '주문생성',
    ORDER_DATE DATE DEFAULT SYSDATE,
    ORDER_METHOD VARCHAR2(30),
    ORDER_PM VARCHAR2(20),
    ORDER_POINT NUMBER DEFAULT 0
);

COMMENT ON COLUMN ORDER_SUM.ORDER_NO IS '주문번호';
COMMENT ON COLUMN ORDER_SUM.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN ORDER_SUM.ORDER_PRICE IS '총 주문금액';
COMMENT ON COLUMN ORDER_SUM.ORDER_STAT IS '주문상태';
COMMENT ON COLUMN ORDER_SUM.ORDER_DATE IS '주문일';
COMMENT ON COLUMN ORDER_SUM.ORDER_METHOD IS '결제수단';
COMMENT ON COLUMN ORDER_SUM.ORDER_PM IS '결제상태';
COMMENT ON COLUMN ORDER_SUM.ORDER_POINT IS '포인트사용';

-- 주문번호 시퀀스 생성
CREATE SEQUENCE SEQ_ORDERNO;

-- 주문상세 테이블
CREATE TABLE ORDER_DETAIL (
    ORDER_NO NUMBER CONSTRAINT OD_NO_FK REFERENCES ORDER_SUM(ORDER_NO) ON DELETE CASCADE,
    MEMBER_NO NUMBER CONSTRAINT OD_MEMBER_NO_FK REFERENCES MEMBER(NO),
    DETAIL_PRO_NO NUMBER,
    DETAIL_PRO_NAME VARCHAR2(100),
    DETAIL_OPT NUMBER,
    DETAIL_OPT_NAME VARCHAR2(40),
    DETAIL_QTY NUMBER,
    DETAIL_PRICE NUMBER CONSTRAINT OD_PRICE_NN NOT NULL,
    PRO_MODIFY_IMG VARCHAR2(4000),
    
    FOREIGN KEY(DETAIL_PRO_NO, DETAIL_OPT) REFERENCES PRODUCT_OPT,
    CONSTRAINT OD_PK PRIMARY KEY(ORDER_NO, DETAIL_PRO_NO, DETAIL_OPT)
);

COMMENT ON COLUMN ORDER_DETAIL.ORDER_NO IS '주문번호';
COMMENT ON COLUMN ORDER_DETAIL.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN ORDER_DETAIL.DETAIL_PRO_NO IS '상품번호';
COMMENT ON COLUMN ORDER_DETAIL.DETAIL_PRO_NAME IS '상품이름';
COMMENT ON COLUMN ORDER_DETAIL.DETAIL_OPT IS '옵션번호';
COMMENT ON COLUMN ORDER_DETAIL.DETAIL_OPT_NAME IS '옵션이름';
COMMENT ON COLUMN ORDER_DETAIL.DETAIL_QTY IS '주문수량';
COMMENT ON COLUMN ORDER_DETAIL.DETAIL_PRICE IS '가격';

-- 배송 테이블
CREATE TABLE DELIVERY (
    ORDER_NO NUMBER CONSTRAINT DEL_O_NO_FK REFERENCES ORDER_SUM(ORDER_NO),
    MEMBER_NO NUMBER CONSTRAINT DEL_MEMBER_NO_FK REFERENCES MEMBER(NO),
    DEL_STAT VARCHAR2(30) DEFAULT '상품준비중',
    DEL_NAME VARCHAR2(20) CONSTRAINT DEL_NAME_NN NOT NULL,
    DEL_POSTCODE VARCHAR2(20),
    DEL_ADD VARCHAR2(200) CONSTRAINT DEL_ADD_NN NOT NULL,
    DEL_EXTRA_ADD VARCHAR2(100),
    DEL_DETAIL_ADD VARCHAR2(100),
    DEL_PHONE VARCHAR2(100) CONSTRAINT DEL_PHONE_NN NOT NULL,
    DEL_MSG VARCHAR2(200),
    DEL_CO VARCHAR2(50),
    DEL_IV NUMBER,
    
    CONSTRAINT DEL_PK PRIMARY KEY(ORDER_NO, MEMBER_NO)
);

COMMENT ON COLUMN DELIVERY.ORDER_NO IS '주문번호';
COMMENT ON COLUMN DELIVERY.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN DELIVERY.DEL_STAT IS '배송상태';
COMMENT ON COLUMN DELIVERY.DEL_NAME IS '수령인';
COMMENT ON COLUMN DELIVERY.DEL_POSTCODE IS '우편번호';
COMMENT ON COLUMN DELIVERY.DEL_ADD IS '배송주소';
COMMENT ON COLUMN DELIVERY.DEL_EXTRA_ADD IS '배송주소-추가정보';
COMMENT ON COLUMN DELIVERY.DEL_DETAIL_ADD IS '배송주소-동호수';
COMMENT ON COLUMN DELIVERY.DEL_PHONE IS '수령인 전화번호';
COMMENT ON COLUMN DELIVERY.DEL_MSG IS '배송 요청사항';
COMMENT ON COLUMN DELIVERY.DEL_CO IS '택배사';
COMMENT ON COLUMN DELIVERY.DEL_IV IS '송장번호';

-- 구매후기 테이블
CREATE TABLE REVIEW (
    ORDER_NO NUMBER CONSTRAINT REV_O_NO_FK REFERENCES ORDER_SUM(ORDER_NO),
    MEMBER_NO NUMBER CONSTRAINT REV_MEMBER_NO_FK REFERENCES MEMBER(NO),
    PRO_NO NUMBER CONSTRAINT REV_PRO_NO_FK REFERENCES PRODUCT(PRO_NO),
    PRO_OPT NUMBER,
    PRO_OPT_NAME VARCHAR2(40),
    REV_DATE DATE DEFAULT SYSDATE,
    REV_TITLE VARCHAR2(100) CONSTRAINT REV_TIT_NN NOT NULL,
    REV_CONTENT VARCHAR2(4000) CONSTRAINT REV_CT_NN NOT NULL,
    ORIGINAL_FILENAME VARCHAR2(1000),
    RENAMED_FILENAME VARCHAR2(1000),
    REV_RATING NUMBER(3,1),
    
    FOREIGN KEY(PRO_NO, PRO_OPT) REFERENCES PRODUCT_OPT,
    CONSTRAINT REV_PK PRIMARY KEY(ORDER_NO, PRO_NO, PRO_OPT)
);

COMMENT ON COLUMN REVIEW.ORDER_NO IS '주문번호';
COMMENT ON COLUMN REVIEW.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN REVIEW.PRO_NO IS '상품번호';
COMMENT ON COLUMN REVIEW.PRO_OPT IS '구매옵션';
COMMENT ON COLUMN REVIEW.REV_DATE IS '작성일';
COMMENT ON COLUMN REVIEW.REV_CONTENT IS '내용';
COMMENT ON COLUMN REVIEW.REV_RATING IS '별점';
COMMENT ON COLUMN REVIEW.PRO_OPT_NAME IS '구매옵션이름';
COMMENT ON COLUMN REVIEW.REV_TITLE IS '리뷰제목';
COMMENT ON COLUMN REVIEW.ORIGINAL_FILENAME IS '리뷰사진원본이름';
COMMENT ON COLUMN REVIEW.RENAMED_FILENAME IS '리뷰사진수정이름';

COMMIT; 

---------------------------
------ 상품 데이터(8개) -----
---------------------------
-- 테스트를 위해 상품등록일, 상품수정일, 판매량, 별점 등을 임의로 입력한 데이터입니다.
INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '비건 립스틱', 10000, '22/03/21', '30g', 'beauty_makeup01.jpg', 'beauty_makeup01.jpg', '비건 립스틱입니다. 동물실험을 하지 않았습니다.', 3, 302, 50, 6, '22/03/21', '4earth 코스메틱', '4.0');

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING
) VALUES (
    SEQ_PRONO.NEXTVAL, '친환경 크림', 12000, '22/02/21', '100ml', 'beauty_skincare01.jpg', 'beauty_skincare01.jpg', '친환경 크림입니다. 동물실험을 하지 않았습니다.', 3, 303, 100, 11, '22/02/21', '4earth 코스메틱', '3.8'
);

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '비건 마카롱', 8000, '22/03/25', '30g', 'food_dessert01.jpg', 'food_dessert01.jpg', '비건 마카롱입니다.', 3, 102, 20, 0, '22/03/25', '4earth 식품', '0');

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '유기농 파스타면', 6000, '22/03/17', '100g', 'food_dry01.jpg', 'food_dry01.jpg', '친환경 유기농 파스타면입니다.', 3, 103, 60, 23, '22/03/17', '4earth 식품', '4.3');

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '비건 샴푸', 15000, '22/03/02', '500ml', 'living_bathroom01.jpg', 'living_bathroom01.jpg', '저자극 비건 샴푸입니다.', 3, 203, 80, 3, '22/03/02', '4earth 코스메틱', '4.4');

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '친환경 비누', 11000, '22/03/24', '80g', 'living_bathroom02.jpg', 'living_bathroom02.jpg', '친환경 페이셜 비누입니다.', 3, 203, 10, 0, '22/03/24', '4earth 코스메틱', '0');

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '야옹츄르', 5000, '22/03/24', '25g', 'pet_cat01.jpg', 'pet_cat01.jpg', '100% 휴먼그레이드 재료로 만든 스틱형 고양이 간식입니다.', 3, 402, 30, 1, '22/03/24', '4earth 펫', '4.5');

INSERT INTO PRODUCT (
    PRO_NO, PRO_NAME, PRO_PRICE, PRO_MODIFY_DATE, PRO_VOL, PRO_IMG, PRO_MODIFY_IMG, PRO_INFO, PRO_STAT, PRO_CAT, PRO_STOCK, PRO_SOLD, PRO_DATE, PRO_MFG, PRO_RATING) 
VALUES (
    SEQ_PRONO.NEXTVAL, '강아지 텐트', 19000, '22/03/01', '1', 'pet_dog01.jpg', 'pet_dog01.jpg', '강아지에게 휴식공간을 선물해주세요.', 3, 401, 5, 0, '22/03/01', '4earth 펫', '0');

COMMIT;

-- 상품 옵션 데이터
-- (상품 옵션은 Admin 페이지 에코샵 상품 > 상품 등록에서 상품을 등록할 때 옵션에 대한 정보도 함께 입력할 수 있도록 수정할 예정이며, 현재는 아래와 같이 각 상품 번호에 대해 직접 INSERT 해줘야 합니다.)
INSERT INTO PRODUCT_OPT VALUES (1, 1, '레드');
INSERT INTO PRODUCT_OPT VALUES (1, 2, '코랄');
INSERT INTO PRODUCT_OPT VALUES (1, 3, '버건디');


-- 구매 테스트용 포인트 10만원 지급
INSERT INTO POINT (
    POINT_NO, MEM_NO, SAVE_DATE, SAVE_CONTENT, SAVE_POINT, SPEND_DATE, DISAPEAR_DATE, SAVE_STATUS
) VALUES (
    SEQ_POINT.NEXTVAL, 2, DEFAULT, '챌린지 달성', 100000, NULL, '22/09/01', DEFAULT
);

COMMIT;




















-------------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------
------------------------ 신고 & 문의 답변 ------------------------
--------------------------------------------------------

------------------------
---- 신고 테이블 ----
------------------------

CREATE TABLE REPORT (
    REPORT_NO NUMBER CONSTRAINT REPORT_NO_PK PRIMARY KEY,
    REPORT_M_NO NUMBER CONSTRAINT REPORT_M_NO_FK REFERENCES MEMBER(NO),
    REPORTED_M_NO NUMBER CONSTRAINT REPORTED_M_NO_FK REFERENCES MEMBER(NO),
    REPORT_DATE DATE DEFAULT SYSDATE,
    REPORT_TITLE VARCHAR2(100),
    REPORT_CONTENT VARCHAR2(500),
    REPORT_CATEGORY VARCHAR2(10) DEFAULT '0' CHECK(REPORT_CATEGORY IN('0', '1', '2', '3', '4', '5', '6', '7', '8', '9')),
    REPORT_STATUS VARCHAR2(10) DEFAULT 'Y' CHECK(REPORT_STATUS IN('Y', 'N'))
);

-- REPORT 테이블 코멘트 입력
COMMENT ON COLUMN REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN REPORT.REPORT_M_NO IS '신고한 회원 번호';
COMMENT ON COLUMN REPORT.REPORTED_M_NO IS '신고받은 회원 번호';
COMMENT ON COLUMN REPORT.REPORT_DATE IS '신고일';
COMMENT ON COLUMN REPORT.REPORT_TITLE IS '신고제목';
COMMENT ON COLUMN REPORT.REPORT_CONTENT IS '신고내용';
COMMENT ON COLUMN REPORT.REPORT_CATEGORY IS '신고분류';
COMMENT ON COLUMN REPORT.REPORT_STATUS IS '신고조치';

-- REPORT 테이블 시퀀스 생성
CREATE SEQUENCE SEQ_RNO;

INSERT INTO REPORT (
    REPORT_NO, 
    REPORT_M_NO, 
    REPORTED_M_NO, 
    REPORT_DATE,
    REPORT_TITLE, 
    REPORT_CONTENT, 
    REPORT_STATUS, 
    REPORT_CATEGORY
) VALUES(
    SEQ_RNO.NEXTVAL, 
    1, 
    2, 
    DEFAULT, 
    '신고합니다', 
    '신고내용~~~~~~~', 
    DEFAULT, 
    '2'
);

INSERT INTO REPORT (
    REPORT_NO, 
    REPORT_M_NO, 
    REPORTED_M_NO, 
    REPORT_DATE,
    REPORT_TITLE, 
    REPORT_CONTENT, 
    REPORT_STATUS, 
    REPORT_CATEGORY
) VALUES(
    SEQ_RNO.NEXTVAL, 
    1, 
    2, 
    DEFAULT, 
    '도배신고합니다', 
    '신고내용~~~~~~~~~~',
    DEFAULT,
    '6'
);

INSERT INTO REPORT (
    REPORT_NO, 
    REPORT_M_NO, 
    REPORTED_M_NO, 
    REPORT_DATE,
    REPORT_TITLE, 
    REPORT_CONTENT, 
    REPORT_STATUS, 
    REPORT_CATEGORY
) VALUES(
    SEQ_RNO.NEXTVAL, 
    2, 
    1, 
    DEFAULT, 
    '광고신고합니다', 
    '신고내용~~~~~~~~~~',
    DEFAULT,
    '1'
);

COMMIT;


CREATE TABLE QNA_ANSWER (
    ANSWER_NO NUMBER CONSTRAINT ANSWER_NO_PK PRIMARY KEY,
    QNA_NO NUMBER CONSTRAINT QNA_ANSWER_NO_FK REFERENCES QNA(QNA_NO) NOT NULL,
    WRITER_NO NUMBER CONSTRAINT QNA_ANSWER_WRITER_NO_FK REFERENCES MEMBER(NO) NOT NULL,
    QNA_ANSWER VARCHAR2(4000),
    ANSWER_STATUS VARCHAR2(3) DEFAULT 'Y',
    ANSWER_DATE DATE DEFAULT SYSDATE);

CREATE SEQUENCE SEQ_QNA_ANSWER;

-- REPORT 테이블 코멘트 입력
COMMENT ON COLUMN QNA_ANSWER.ANSWER_NO IS '문의답변번호';
COMMENT ON COLUMN QNA_ANSWER.QNA_NO IS '문의번호';
COMMENT ON COLUMN QNA_ANSWER.WRITER_NO IS '문의자번호';
COMMENT ON COLUMN QNA_ANSWER.QNA_ANSWER IS '문의답변';
COMMENT ON COLUMN QNA_ANSWER.ANSWER_STATUS IS '문의종류';
COMMENT ON COLUMN QNA_ANSWER.ANSWER_DATE IS '문의날짜';

COMMIT;


