
DROP TABLE NOTICE;
DROP SEQUENCE SEQ_NOTICE_NO;

DROP TABLE QNA;
DROP SEQUENCE SEQ_QNA_NO;

DROP TABLE QNA_CATEGORY;


--------------------------------------------------------
------------------------ 공지사항 & 1:1문의 ------------------------
--------------------------------------------------------

------------------------
---- 공지사항 테이블 ----
------------------------


CREATE TABLE NOTICE (
    NOTICE_NO NUMBER CONSTRAINT NOTICE_NO_PK PRIMARY KEY,
    WRITER_NO NUMBER CONSTRAINT NOTICE_WRITER_NO_FK REFERENCES MEMBER(NO),
    NOTICE_TIT VARCHAR2(100) CONSTRAINT NOTICE_TIT_NN NOT NULL,
    NOTICE_CONTENT VARCHAR2(2000) CONSTRAINT NOTICE_CONTENT_NN NOT NULL,
    NOTICE_COUNT NUMBER DEFAULT 0,
    ORIGINAL_FILENAME VARCHAR2(100),
    RENAMED_FILENAME VARCHAR2(100),
    DATE_WRITEN DATE DEFAULT SYSDATE,
    DATE_WRITEN_MODIFY DATE DEFAULT SYSDATE,
    NOTICE_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK(NOTICE_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN NOTICE.NOTICE_NO IS '게시글번호';
COMMENT ON COLUMN NOTICE.WRITER_NO IS '회원번호';
COMMENT ON COLUMN NOTICE.NOTICE_TIT IS '제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOTICE_COUNT IS '조회수';
COMMENT ON COLUMN NOTICE.ORIGINAL_FILENAME IS '원본파일이름';
COMMENT ON COLUMN NOTICE.RENAMED_FILENAME IS '수정된파일이름';
COMMENT ON COLUMN NOTICE.DATE_WRITEN IS '게시글작성일';
COMMENT ON COLUMN NOTICE.DATE_WRITEN_MODIFY IS '게시글수정일';
COMMENT ON COLUMN NOTICE.NOTICE_STATUS IS '상태';


CREATE SEQUENCE SEQ_NOTICE_NO;



BEGIN
    FOR N IN 1..52
    LOOP
        INSERT INTO NOTICE VALUES(SEQ_NOTICE_NO.NEXTVAL, '1', 'REVIEW 게시글테스트 ' || SEQ_NOTICE_NO.CURRVAL , 'REVIEW 게시글테스트중입니다 ' || SEQ_NOTICE_NO.CURRVAL, DEFAULT, NULL, NULL, DEFAULT, DEFAULT, DEFAULT);
    END LOOP;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
END;
/

COMMIT;

------------------------
---- 1:1문의 테이블 ----
------------------------

DROP TABLE QNA;
DROP SEQUENCE SEQ_QNA_NO;
DROP TABLE QNA_CATEGORY;


-- QNA 카테고리 테이블
CREATE TABLE QNA_CATEGORY (
    C_NO NUMBER(5) CONSTRAINT QNA_CATEGORY_C_NO_PK PRIMARY KEY,
    C_NAME VARCHAR2(30) CONSTRAINT QNA_CATEGORY_C_NAME_NN NOT NULL
);

COMMENT ON COLUMN QNA_CATEGORY.C_NO IS '카테고리번호';
COMMENT ON COLUMN QNA_CATEGORY.C_NAME IS '카테고리명';


-- 카테고리 데이터
INSERT INTO QNA_CATEGORY VALUES (0101, '챌린지수행관련문의');
INSERT INTO QNA_CATEGORY VALUES (0102, '포인트관련문의');
INSERT INTO QNA_CATEGORY VALUES (0103, '챌린지오류관련문의');
INSERT INTO QNA_CATEGORY VALUES (0201, '구매');
INSERT INTO QNA_CATEGORY VALUES (0202, '환불');
INSERT INTO QNA_CATEGORY VALUES (0203, '포인트');
INSERT INTO QNA_CATEGORY VALUES (0301, '가입');
INSERT INTO QNA_CATEGORY VALUES (0302, '탈퇴');
INSERT INTO QNA_CATEGORY VALUES (0303, '정보수정');
INSERT INTO QNA_CATEGORY VALUES (0401, '기타');

-- 1:1문의 테이블
CREATE TABLE QNA (
    QNA_NO NUMBER CONSTRAINT QNA_NO_PK PRIMARY KEY,
    WRITER_NO NUMBER CONSTRAINT QNA_WRITER_NO_FK REFERENCES MEMBER(NO),
    QNA_TIT VARCHAR2(100) CONSTRAINT QNA_TIT_NN NOT NULL,
    QNA_CAT NUMBER CONSTRAINT QNA_CAT_FK REFERENCES QNA_CATEGORY(C_NO),
    QNA_CONTENT VARCHAR2(2000) CONSTRAINT QNA_CONTENT_NN NOT NULL,
    QNA_COUNT NUMBER DEFAULT 0,
    ORIGINAL_FILENAME VARCHAR2(100),
    RENAMED_FILENAME VARCHAR2(100),
    DATE_WRITEN DATE DEFAULT SYSDATE,
    DATE_WRITEN_MODIFY DATE DEFAULT SYSDATE,
    QNA_STATUS VARCHAR2(2) DEFAULT 'Y' CHECK(QNA_STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN QNA.QNA_NO IS '게시글번호';
COMMENT ON COLUMN QNA.WRITER_NO IS '회원번호';
COMMENT ON COLUMN QNA.QNA_TIT IS '제목';
COMMENT ON COLUMN QNA.QNA_CAT IS '카테고리명';
COMMENT ON COLUMN QNA.QNA_CONTENT IS '내용';
COMMENT ON COLUMN QNA.QNA_COUNT IS '조회수';
COMMENT ON COLUMN QNA.ORIGINAL_FILENAME IS '원본파일이름';
COMMENT ON COLUMN QNA.RENAMED_FILENAME IS '수정된파일이름';
COMMENT ON COLUMN QNA.DATE_WRITEN IS '게시글작성일';
COMMENT ON COLUMN QNA.DATE_WRITEN_MODIFY IS '게시글수정일';
COMMENT ON COLUMN QNA.QNA_STATUS IS '상태';

CREATE SEQUENCE SEQ_QNA_NO;

commit;